name: toolist
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  get_storage: 2.0.3
  flutter_dotenv: 5.0.2
  supabase: 0.2.5
  dartz: 0.10.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - .env
    - images/
  uses-material-design: true

